name: erp_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  http:
  fluttertoast: ^9.0.0
  local_auth: ^2.3.0
  flutter_native_splash: ^2.4.6
  logger:
  shared_preferences:
  camera: ^0.11.2
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  google_fonts: ^6.3.2
  dio: ^5.9.0
  file_picker: ^10.3.3
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0
  flutter_windowmanager_plus: ^1.0.1
  mime: ^2.0.0
  syncfusion_flutter_pdfviewer: ^31.1.23
  http_parser: ^4.1.2
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Appicon/play_store_512.png"
  adaptive_icon_foreground: "assets/Appicon/play_store_512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Appicon/
    - assets/model/mobilefacenet.tflite
    - .env.dev
    - .env.staging
    - .env.prod    

flutter_native_splash:
  color: "#12c721"
  image: assets/Appicon/play_store_512.png
  android_12:
    image: assets/Appicon/play_store_512.png
    color: "#12c721"
